site_name: CrossGL Documentation
site_url: https://crossgl.github.io/crossgl-docs
theme:
    name: material
    logo: assets/logo.png
    favicon: assets/favicon.ico
    icon:
      repo: fontawesome/brands/github
    palette: 
      scheme: slate
      primary: indigo
      accent: red
    features:
      - header.autohide
      - navigation.tabs
      - navigation.sections
      - navigation.expand
      - navigation.path
      - navigation.indexes
      - navigation.instant
      - navigation.instant.progress
      - content.code.copy

markdown_extensions: 
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
repo_url: https://github.com/CrossGL/
repo_name: CrossGL

extra_css:
  - stylesheets/extra.css
nav:
  - HOME: pages/index.md
  - DYSON: 
    - OVERVIEW: pages/dyson/overview.md
    - GETTING STARTED: pages/dyson/getting-started.md
    - BILLING: pages/dyson/billing.md
  - GRAPHICA: 
    - OVERVIEW: pages/graphica/graphica.md
    - LANGUAGE: pages/graphica/language.md
    # - DESIGN: pages/graphica/design.md
    - API REFERENCE: pages/graphica/api_reference.md
    - CONTRIBUTION : pages/graphica/graphica_contribution.md
   
    