name: Deploy Sphinx Documentation

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx-rtd-theme furo

    - name: Build documentation
      run: |
        sphinx-build -b html source/ docs/build/html

    - name: Check build directory
      run: |
        ls -al ./docs/build/html  # Verify the build output

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./docs/build/html
